### ISSUE TITLE
Verify add resource end point

### ISSUE THREAD

**Issue by mamillapalli** [mamillapalli/Assist#19]

**Comment by sreenivas4092** [comment]
Verfied Add Resource End point. Add sreenivas resource as below

![image](https://user-images.githubusercontent.com/10458842/184186558-b4ac13a1-69b5-4499-bf51-c92c1ec20cba.png)

We can see newly added resource in the GET resource end point
![image](https://user-images.githubusercontent.com/10458842/184186924-09d726a9-3565-4914-a258-4d44a500a4ff.png)
