### ISSUE TITLE
Verify get Resource Roles End point

### ISSUE THREAD

**Issue by mamillapalli** [mamillapalli/Assist#27]

**Comment by sreenivas4092** [comment]
Get Roles API is verified


![image](https://user-images.githubusercontent.com/10458842/184179228-49f5e789-0402-4556-a931-5833ef7be4c4.png)

**Comment by sreenivas4092** [comment]
Verified Get Resource roles end point.

![image](https://user-images.githubusercontent.com/10458842/184285452-cd156137-20b1-4833-9282-2da8339d79a3.png)
